logging:
  level: debug
  formatter:
    name: text
    options:
      disable_timestamp: true

# gRPC MDA
mda:
  port: 8180

# gRPC MTA
mta:
  port: 8125

# Database config
database:
  host: localhost
  port: 1234
  max_open_conns: 20
  database_name: federizer
  ssl:
    mode: disable
    root_cert: ""
    cert: ""
    Key: ""
  admin:
    username: postgres
    password: password
  user:
    username: fuser
    password: fpassword