domainName: cargomail.org
storagePath: ./storage/cargomail.org
databasePath: ./storage/cargomail.org/database/cargomail.db
resourcesPath: ./storage/cargomail.org/resources/
emailAddressCertPath: ./storage/cargomail.org/certificates/server.crt
emailAddressKeyPath: ./storage/cargomail.org/certificates/server.key
emailAddressBind: 127.0.0.1:8181
emailAddressBindTLS: 127.0.0.1:2125
mailboxCertPath: ./storage/cargomail.org/certificates/server.crt
mailboxKeyPath: ./storage/cargomail.org/certificates/server.key
mailboxBind: 127.0.0.1:8182
mailboxBindTLS: 127.0.0.1:2126
cookieSameSite: strict