domainName: cargomail.org
storagePath: ./storage/cargomail.org
databasePath: ./storage/cargomail.org/database/cargomail.db
resourcesPath: ./storage/cargomail.org/resources/
mtaCertPath: ./storage/cargomail.org/certificates/server.crt
mtaKeyPath: ./storage/cargomail.org/certificates/server.key
rtaCertPath: ./storage/cargomail.org/certificates/server.crt
rtaKeyPath: ./storage/cargomail.org/certificates/server.key
providerBind: 127.0.0.1:8181
mtaBind: 127.0.0.1:2125
rtaBind: 127.0.0.1:2135
cookieSameSite: strict