domainName: cargomail.org
storagePath: ./storage/cargomail.org
databasePath: ./storage/cargomail.org/database/cargomail.db
resourcesPath: ./storage/cargomail.org/resources/
mailServiceCertPath: ./storage/cargomail.org/certificates/server.crt
mailServiceKeyPath: ./storage/cargomail.org/certificates/server.key
mailServiceBind: 127.0.0.1:8181
mailServiceBindTLS: 127.0.0.1:2125
mailboxServiceCertPath: ./storage/cargomail.org/certificates/server.crt
mailboxServiceKeyPath: ./storage/cargomail.org/certificates/server.key
mailboxServiceBind: 127.0.0.1:8182
mailboxServiceBindTLS: 127.0.0.1:2126
cookieSameSite: strict