domainName: cargomail.org
dohProviderHost: "cloudflare-dns.com"
storagePath: ./storage/cargomail.org
databasePath: ./storage/cargomail.org/database/cargomail.db
resourcesPath: ./storage/cargomail.org/resources/
mssClientCertPath: ./storage/cargomail.org/certificates/mss-client.crt
mssClientKeyPath: ./storage/cargomail.org/certificates/mss-client.key
mssServerCertPath: ./storage/cargomail.org/certificates/mss-server.crt
mssServerKeyPath: ./storage/cargomail.org/certificates/mss-server.key
mssBind: 127.0.0.1:8180
mssBindTLS: 127.0.0.1:2124
mhsClientCertPath: ./storage/cargomail.org/certificates/mhs-client.crt
mhsClientKeyPath: ./storage/cargomail.org/certificates/mhs-client.key
mhsServerCertPath: ./storage/cargomail.org/certificates/mhs-server.crt
mhsServerKeyPath: ./storage/cargomail.org/certificates/mhs-server.key
mhsBind: 127.0.0.1:8181
mhsBindTLS: 127.0.0.1:2125
mdsClientCertPath: ./storage/cargomail.org/certificates/mds-client.crt
mdsClientKeyPath: ./storage/cargomail.org/certificates/mds-client.key
mdsServerCertPath: ./storage/cargomail.org/certificates/mds-server.crt
mdsServerKeyPath: ./storage/cargomail.org/certificates/mds-server.key
mdsBind: 127.0.0.1:8182
mdsBindTLS: 127.0.0.1:2126
rhsClientCertPath: ./storage/cargomail.org/certificates/rhs-client.crt
rhsClientKeyPath: ./storage/cargomail.org/certificates/rhs-client.key
rhsServerCertPath: ./storage/cargomail.org/certificates/rhs-server.crt
rhsServerKeyPath: ./storage/cargomail.org/certificates/rhs-server.key
rhsBind: 127.0.0.1:8183
rhsBindTLS: 127.0.0.1:2127
cookieSameSite: strict