domainName: ${DOMAIN_NAME}
dohProviderHost: ${DOH_PROVIDER_HOST}
storagePath: ${STORAGE_PATH}
databasePath: ${DATABASE_PATH}
resourcesPath: ${RESOURCES_PATH}
mssClientCertPath: ${MSS_CLIENT_CERT_PATH}
mssClientPeyPath: ${MSS_CLIENT_KEY_PATH}
mssServerCertPath: ${MSS_SERVER_CERT_PATH}
mssServerPeyPath: ${MSS_SERVER_KEY_PATH}
mssBind: ${MSS_SERVER_BIND}
mssBindTLS: ${MSS_SERVER_BIND_TLS}
mhsClientCertPath: ${MHS_CLIENT_CERT_PATH}
mhsClientPeyPath: ${MHS_CLIENT_KEY_PATH}
mhsServerCertPath: ${MHS_SERVER_CERT_PATH}
mhsServerPeyPath: ${MHS_SERVER_KEY_PATH}
mhsBind: ${MHS_SERVER_BIND}
mhsBindTLS: ${MHS_SERVER_BIND_TLS}
mdsClientCertPath: ${MDS_CLIENT_CERT_PATH}
mdsClientPeyPath: ${MDS_CLIENT_KEY_PATH}
mdsServerCertPath: ${MDS_SERVER_CERT_PATH}
mdsServerPeyPath: ${MDS_SERVER_KEY_PATH}
mdsBind: ${MDS_SERVER_BIND}
mdsBindTLS: ${RHS_SERVER_BIND_TLS}
rhsClientCertPath: ${RHS_CLIENT_CERT_PATH}
rhsClientPeyPath: ${RHS_CLIENT_KEY_PATH}
rhsServerCertPath: ${RHS_SERVER_CERT_PATH}
rhsServerPeyPath: ${RHS_SERVER_KEY_PATH}
rhsBind: ${RHS_SERVER_BIND}
rhsBindTLS: ${RHS_SERVER_BIND_TLS}
cookieSameSite: ${COOKIE_SAME_SITE}

