domainName: ${DOMAIN_NAME}
dohProviderHost: ${DOH_PROVIDER_HOST}
storagePath: ${STORAGE_PATH}
databasePath: ${DATABASE_PATH}
resourcesPath: ${RESOURCES_PATH}
mailServiceCertPath: ${MAIL_SERVICE_CERT_PATH}
mailServicePeyPath: ${MAIL_SERVICE_KEY_PATH}
mailServiceBind: ${MAIL_SERVICE_BIND}
mailServiceBindTLS: ${MAIL_SERVICE_BIND_TLS}
mailboxServiceCertPath: ${MAILBOX_SERVICE_CERT_PATH}
mailboxServicePeyPath: ${MAILBOX_SERVICE_KEY_PATH}
mailboxServiceBind: ${MAILBOX_SERVICE_BIND}
mailboxServiceBindTLS: ${MAILBOX_SERVICE_BIND_TLS}
cookieSameSite: ${COOKIE_SAME_SITE}

