export const INBOX = '/'
export const DONE = '/done'
export const DRAFTS = '/drafts'
export const TRASH = '/trash'
export const ACCOUNT = '/account'
export const LOGIN = '/login'
export const NOT_FOUND = '*'
