logging:
  level: info 
  formatter:
    name: text
    options:
      disable_timestamp: true

# OIDC
oidc:
  issuer: http://localhost:9998
  key_path: ../cargomail-zitadel-oidc/example/server/service-key1.json    

# gRPC Webmail
webmail:
  port: 8080
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]
    allowed_headers:
      [
        "origin",
        "content-type",
        "accept",
        "accept-language",
        "authorization",
        "x-grpc-web",
        "x-user-agent",
        "client-sent-security-token",
        "x-requested-with",
      ]
    max_age: 600
    allow_credentials: true
      
# gRPC MTA
mta:
  port: 8025

# Database config
database:
  host: localhost
  port: 1234
  max_open_conns: 20
  ssl:
    mode: disable
    root_cert: ""
    cert: ""
    Key: ""
  admin:
    username: postgres
    password: password
  user:
    database_name: cargomail
    username: cargouser
    password: cupassword