logging:
  level: info
  formatter:
    name: text
    options:
      disable_timestamp: true

# OIDC
oidc:
  issuer: http://localhost:9998
  key_path: ../cargomail-zitadel-oidc/example/server/service-key1.json

# Mailbox
mailbox:
  uri: http://localhost:8080
  port: 8080
  cors:
    allowed_origins: ["*"]
    allowed_methods:
      ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]
    allowed_headers:
      [
        "origin",
        "content-type",
        "accept",
        "accept-language",
        "authorization",
        "x-grpc-web",
        "x-user-agent",
        "client-sent-security-token",
        "x-requested-with",
        "x-request-id",
        "x-http-method-override",
        "content-type",
        "upload-length",
        "upload-offset"
        "sha256sum",
        "tus-resumable",
        "upload-metadata",
        "upload-defer-length",
        "upload-concat",
      ]
    max_age: 600
    allow_credentials: true

# iMTA
imta:
  domain: localhost:8025
  port: 8025

# Database
database:
  host: localhost
  port: 1234
  max_open_conns: 20
  ssl:
    mode: disable
    root_cert: ""
    cert: ""
    Key: ""
  admin:
    username: postgres
    password: password
  user:
    database_name: cargomail
    username: cargouser
    password: cupassword

# Filestore
filestore:
  path: ./storage
  base_path: /files/
