domainName: ${DOMAIN_NAME}
storagePath: ${STORAGE_PATH}
databasePath: ${DATABASE_PATH}
resourcesPath: ${RESOURCES_PATH}
mtaCertPath: ${MTA_CERT_PATH}
mtaPeyPath: ${MTA_KEY_PATH}
rtaCertPath: ${RTA_CERT_PATH}
rtaPeyPath: ${RTA_KEY_PATH}
providerBind: ${PROVIDER_BIND}
mtaBind: ${MTA_BIND}
rtaBind: ${RTA_BIND}
cookieSameSite: ${COOKIE_SAME_SITE}

