domainName: ${DOMAIN_NAME}
storagePath: ${STORAGE_PATH}
databasePath: ${DATABASE_PATH}
resourcesPath: ${RESOURCES_PATH}
transferCertPath: ${TRANSFER_CERT_PATH}
transferPeyPath: ${TRANSFER_KEY_PATH}
providerBind: ${PROVIDER_BIND}
transferBind: ${TRANSFER_BIND}
cookieSameSite: ${COOKIE_SAME_SITE}

