domainName: ${DOMAIN_NAME}
storagePath: ${STORAGE_PATH}
databasePath: ${DATABASE_PATH}
resourcesPath: ${RESOURCES_PATH}
mailboxCertPath: ${MAILBOX_CERT_PATH}
mailboxPeyPath: ${MAILBOX_KEY_PATH}
emailCertPath: ${EMAIL_CERT_PATH}
emailPeyPath: ${EMAIL_KEY_PATH}
mailboxBind: ${MAILBOX_BIND}
emailBind: ${EMAIL_BIND}
cookieSameSite: ${COOKIE_SAME_SITE}

